services:
  web3-auth-backend:
    container_name: web3-auth-backend
    build:
      context: ./web3-auth-backend
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      NODE_ENV: ${NODE_ENV}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_KEY_ID: ${JWT_KEY_ID}
      ETH_RPC_URL: ${ETH_RPC_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
    ports:
      - "3000:3000"

  api:
    container_name: api
    build:
      context: ./api
    environment:
      ETH_RPC_URL: ${ETH_RPC_URL}
      EULER_OPERATOR: ${EULER_OPERATOR}
      EULER_VAULT_FACTORY: ${EULER_VAULT_FACTORY}
      REBALANCING_OPERATOR_PK: ${REBALANCING_OPERATOR_PK}
      REBALANCING_OPERATOR_ADDRESS: ${REBALANCING_OPERATOR_ADDRESS}
      USDC_ADDRESS: ${USDC_ADDRESS}
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        VITE_WEB3_AUTH_VERIFIER: ${VITE_WEB3_AUTH_VERIFIER}
        VITE_WEB3_AUTH_CLIENTID: ${VITE_WEB3_AUTH_CLIENTID}
        VITE_WEB3_AUTH_API_URL: ${VITE_WEB3_AUTH_API_URL}
        VITE_API_URL: ${VITE_API_URL}
        VITE_ETH_RPC_URL: ${VITE_ETH_RPC_URL}
    depends_on:
      - web3-auth-backend
    ports:
      - "4173:4173"
